[package]
name = "maperick"
version = "0.1.0"
edition = "2021"

[features]
default = ["crossterm"]

[dependencies]
bitflags = "1.3"
cassowary = "0.3"
unicode-segmentation = "1.2"
unicode-width = "0.1"
termion = { version = "1.5", optional = true }
crossterm = { version = "0.22", optional = true }
serde = { version = "1", optional = true, features = ["derive"]}
tui = "0.18.0"
rand = "0.8"
argh = "0.1"

[dev-dependencies]
rand = "0.8"
argh = "0.1"
